<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-03-07T22:29:25Z" name="FreeCRM App Automation Test Suite" finished-at="2018-03-07T22:29:58Z" duration-ms="33008">
    <groups>
    </groups>
    <test started-at="2018-03-07T22:29:25Z" name="FreeCRMTest" finished-at="2018-03-07T22:29:58Z" duration-ms="33008">
      <class name="com.freeCRM.qa.testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:25Z" name="setUp" finished-at="2018-03-07T17:29:32Z" duration-ms="6939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageTitleTest()[pri:1, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:32Z" name="loginPageTitleTest" finished-at="2018-03-07T17:29:32Z" duration-ms="31" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.freeCRM.qa.testcases.LoginTest.loginPageTitleTest(LoginTest.java:30)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:32Z" name="tearDown" finished-at="2018-03-07T17:29:32Z" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:32Z" name="setUp" finished-at="2018-03-07T17:29:37Z" duration-ms="5257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageTitleTest()[pri:1, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:37Z" name="loginPageTitleTest" finished-at="2018-03-07T17:29:37Z" duration-ms="12" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.freeCRM.qa.testcases.LoginTest.loginPageTitleTest(LoginTest.java:30)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:37Z" name="tearDown" finished-at="2018-03-07T17:29:37Z" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:37Z" name="setUp" finished-at="2018-03-07T17:29:42Z" duration-ms="4839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageTitleTest()[pri:1, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:42Z" name="loginPageTitleTest" finished-at="2018-03-07T17:29:42Z" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [#1 Free CRM for Any Business: Online Customer Relationship Softwar] but found [#1 Free CRM for Any Business: Online Customer Relationship Software]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.freeCRM.qa.testcases.LoginTest.loginPageTitleTest(LoginTest.java:30)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:42Z" name="tearDown" finished-at="2018-03-07T17:29:42Z" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:42Z" name="setUp" finished-at="2018-03-07T17:29:48Z" duration-ms="6095" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageLogoTest()[pri:2, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:48Z" name="loginPageLogoTest" finished-at="2018-03-07T17:29:48Z" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageLogoTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:48Z" name="tearDown" finished-at="2018-03-07T17:29:48Z" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:48Z" name="setUp" finished-at="2018-03-07T17:29:52Z" duration-ms="4074" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginCheckTest()[pri:3, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:52Z" name="loginCheckTest" finished-at="2018-03-07T17:29:58Z" duration-ms="5132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCheckTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.freeCRM.qa.testcases.LoginTest@3246fb96]" started-at="2018-03-07T17:29:58Z" name="tearDown" finished-at="2018-03-07T17:29:58Z" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.freeCRM.qa.testcases.LoginTest -->
    </test> <!-- FreeCRMTest -->
  </suite> <!-- FreeCRM App Automation Test Suite -->
</testng-results>
